version: '3.7'
services:
  traefik:
    image: traefik:v2.2.1
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname==swarm-primary-manager 
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik-api.loadbalancer.server.port=8080"

        - "traefik.http.routers.traefik-api-insecure.entrypoints=insecure"
        - "traefik.http.routers.traefik-api-insecure.rule=Host(`traefik.example.org`)"
        - "traefik.http.middlewares.traefik-api-insecure-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.traefik-api-insecure.middlewares=traefik-api-insecure-redirect"

        - "traefik.http.routers.traefik-api.entrypoints=secure"
        - "traefik.http.routers.traefik-api.rule=Host(`traefik.example.org`)"
        - "traefik.http.routers.traefik-api.tls.certresolver=letsencrypt"
        # create PASSWORD-HASH with 'openssl passwd -apr1 | sed -e s/\\$/\\$\\$/g'
        - "traefik.http.middlewares.traefik-api-auth.basicauth.users=user:xxx"
        - "traefik.http.routers.traefik-api.middlewares=traefik-api-auth"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yml
    volumes:
      - traefik-acme-data:/traefik-data
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    image: portainer/portainer:1.24.0
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - portainer
      - proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

        - "traefik.http.routers.portainer-insecure.entrypoints=insecure"
        - "traefik.http.routers.portainer-insecure.rule=Host(`portainer.example.org`)"
        - "traefik.http.middlewares.portainer-insecure-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.portainer-insecure.middlewares=portainer-insecure-redirect"

        - "traefik.http.routers.portainer.entrypoints=secure"
        - "traefik.http.routers.portainer.rule=Host(`portainer.example.org`)"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"

  portainer-agent:
    image: portainer/agent:1.6.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer
    deploy:
      mode: global

volumes:
  traefik-acme-data:
    driver: hetzner
    driver_opts:
      size: '10'
  portainer-data:
    driver: hetzner
    driver_opts:
      size: '10'

configs:
  traefik-config:
    file: ./traefik.yml

networks:
  proxy:
    driver: overlay
    driver_opts:
      encrypted: "true"
  portainer:
    driver: overlay
    driver_opts:
      encrypted: "true"
