---
- hosts: swarm-primary-manager
  remote_user: root
  tasks:
    - name: drain the node
      shell: "docker node update --availability drain {{ target }}"

- hosts: "{{ target }}"
  remote_user: root
  tasks:
    - name: reboot and wait
      reboot:

- hosts: swarm-primary-manager
  remote_user: root
  tasks:
    - name: activate the node
      shell: "docker node update --availability active {{ target }}"
